name: Deploy to Cloud Run and Update Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy-cloud-run:
    if: "contains(github.event.head_commit.message, '[CloudRun]')" # Trigger if CloudRun changes are detected
    runs-on: ubuntu-22.04
    permissions:
      contents: read 
      id-token: write  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: "graphulator" 
          workload_identity_provider: "projects/598507763983/locations/global/workloadIdentityPools/github/providers/graphulator"
          service_account: "598507763983-compute@developer.gserviceaccount.com"

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/graphulator/graphulator/graphulator-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy graphulator-app \
            --image us-central1-docker.pkg.dev/graphulator/graphulator/graphulator-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

  update-cloud-storage:
    if: "contains(github.event.head_commit.message, '[CloudStorage]')" # Trigger if CloudStorage changes are detected
    runs-on: ubuntu-22.04
    permissions:
      contents: read 
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: "graphulator"
          workload_identity_provider: "projects/598507763983/locations/global/workloadIdentityPools/github/providers/graphulator"

      - name: Upload HTML to Cloud Storage
        run: |
          gsutil cp ./Graphulator.html gs://graphulator/