name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
  #  - name: Build the Docker image
  #    run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - uses: 'google-github-actions/auth@v2'
      id: authent
      name: Authenticate to GCP
      with:
        project_id: 'name of the gcp project'
        workload_identity_provider: "if we have one"
    
    - name: gcloud use Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
    
    - name: buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64, linus/arm64
      
    - name: Build and Push image
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: use-central1-docker.pkg.dev/project_id/Graphulator/docker_repo:v1
      
      
